<?php
include_once('../../controller/tecnologia/Sistema.php');

date_default_timezone_set('America/Sao_Paulo');

$connect = Sistema::getConexao();
$pendente = Sistema::getGet('pendente');
$usuario = $_SESSION['handleUsuario'];
$start = $_GET["start"];
$length = $_GET["length"] + $start;
$search = $_GET["pesquisa"];

$order = $_GET["order"];
$columns = $_GET["columns"];
$col = 0;
$dir = "desc";

if (!empty($order)) {
    foreach ($order as $o) {
        $col = $o['column'];
        $dir = $o['dir'];
    }
}

$where = [];
$whereOr = [];

$where[] = " A.TRANSPORTADOR IN (".Sistema::getPessoaUsuarioToStr($connect).") 
     
		
	AND NOT EXISTS (SELECT X.HANDLE 
	                  FROM OP_AGRUPAMENTORECEBIMENTO X
					 INNER JOIN SP_RECEBIMENTOFISICO X1 ON X1.HANDLE = X.RECEBIMENTOFISICO 
					 WHERE X.AGRUPAMENTO = A.HANDLE 
					   AND X1.STATUS <> 6)";

if ($pendente == 'true') {
    $where[] = "A.STATUS NOT IN (5, 37, 1, 2, 6)";
}
else {
	$where[] = "A.STATUS NOT IN (1, 2, 6)";
}

if ($search) {
    if (intval($search) !== 0) {
        $whereOr[] = "B3.NUMERO = '" . intval($search) . "'";
    }

}

if (count($whereOr) > 0) {
    $where[] = '(' . join(' OR ', $whereOr) . ')';
}

$whereTexto = '';
if (count($where) > 0) {
    $whereTexto = "WHERE " . join(' AND ', $where);
}

$order = "ORDER BY A." . $columns[$col]["data"] . " " . $dir;

$sqlOrdens = "WITH ORDENS AS
(
SELECT ROW_NUMBER() OVER ($order) ROW_NUMBER,
B3.NUMERO DOCUMENTO,
A.HANDLE,
B2.NOME STATUSNOME,
B16.RESOURCENAME,
B4.SIGLA TIPODOCUMENTO,
B5.SIGLA FILIAL,
B6.SIGLA FILIALTRANSPORTE,
B3.DATAEMISSAO,
B7.APELIDO,
B8.NOME MUNICIPIOORIGEM,
B9.SIGLA ESTADOORIGEM,
B10.NOME MUNICIPIODESTINO,
B11.SIGLA ESTADODESTINO,
B1.QUANTIDADE,
B1.QUANTIDADEVOLUME,
B1.PESO,
B1.PESOCUBADO,
B1.PESOLOTACAO,
B1.VOLUME,
(SELECT SUM(X.VALOR) 
   FROM OP_AGRUPAMENTOCOMPOSICAO X
  WHERE X.AGRUPAMENTO = A.HANDLE) VALORBRUTO,
B1.VALORMERCADORIA,
B1.PRAZOENTREGA,
B1.PREVISAOENTREGA,
B1.ENTREGUEEM,
B1.ENTREGUEDIA,
COALESCE(B12.APELIDO, B20.APELIDO) REMETENTE,
COALESCE(B13.APELIDO, B21.APELIDO) DESTINATARIO,
B14.APELIDO TOMADOR,
B15.NOME NATUREZAMERCADORIA,
A.TRANSPORTADOR,
B3.TIPODOCUMENTOFISCAL,
B17.LOGIN USUARIOALTERACAO,
B18.APELIDO AEROPORTODESTINO,
B19.NUMEROMANIFESTO MANIFESTO
FROM OP_AGRUPAMENTO A  
LEFT JOIN GD_DOCUMENTO B3 ON B3.HANDLE = A.DOCUMENTO
LEFT JOIN GD_DOCUMENTOTRANSPORTE B1 ON B1.HANDLE = B3.DOCUMENTOTRANSPORTE
LEFT JOIN GD_STATUSDOCUMENTOTRANSPORTE B2 ON B1.STATUS = B2.HANDLE 
AND ((NOT EXISTS (SELECT HANDLE 
			FROM MS_OPERACAOPAPELUSUARIO 
			WHERE OPERACAO = B3.OPERACAO)
 OR EXISTS (SELECT HANDLE 
			FROM MS_OPERACAOPAPELUSUARIO 
             
			WHERE OPERACAO = B3.OPERACAO 
			AND PAPEL IN (SELECT PAPEL 
				FROM MS_USUARIOPAPEL 
                                                              
				WHERE USUARIO = $usuario))))  
AND ((B3.EHRH <> 'S') OR (EXISTS (SELECT Z0.HANDLE                                             
			FROM MS_USUARIOPAPEL Z0                                            
			INNER JOIN MS_PAPEL Z1 ON Z1.HANDLE = Z0.PAPEL                                            
			WHERE Z0.USUARIO = $usuario                                              
			AND Z1.EHVISUALIZARRECURSOSHUMANOS <> 'S'))) 
LEFT JOIN TR_TIPODOCUMENTO B4 ON B3.TIPODOCUMENTOFISCAL = B4.HANDLE 
LEFT JOIN MS_FILIAL B5 ON B3.FILIAL = B5.HANDLE 
LEFT JOIN MS_FILIAL B6 ON B1.FILIALTRANSPORTE = B6.HANDLE 
LEFT JOIN MS_PESSOA B7 ON A.TRANSPORTADOR = B7.HANDLE 
LEFT JOIN MS_MUNICIPIO B8 ON B1.MUNICIPIOORIGEM = B8.HANDLE 
LEFT JOIN MS_ESTADO B9 ON B8.ESTADO = B9.HANDLE 
LEFT JOIN MS_MUNICIPIO B10 ON B1.MUNICIPIODESTINO = B10.HANDLE 
LEFT JOIN MS_ESTADO B11 ON B10.ESTADO = B11.HANDLE 
LEFT JOIN MS_PESSOA B12 ON B1.REMETENTE = B12.HANDLE 
LEFT JOIN MS_PESSOA B13 ON B1.DESTINATARIO = B13.HANDLE 
LEFT JOIN MS_PESSOA B14 ON B3.PESSOA = B14.HANDLE 
LEFT JOIN MT_NATUREZAMERCADORIA B15 ON B1.NATUREZAMERCADORIA = B15.HANDLE
LEFT JOIN MD_IMAGEM B16 ON B2.IMAGEM = B16.HANDLE
LEFT JOIN MS_USUARIO B17 ON A.LOGUSUARIOALTERACAO = B17.HANDLE
LEFT JOIN MS_PESSOA B18 ON B18.HANDLE = B1.AEROPORTODESTINO
LEFT JOIN OP_MANIFESTO B19 ON B19.HANDLE = A.MANIFESTO
LEFT JOIN MS_PESSOA B20 ON B20.HANDLE = B19.REMETENTE
LEFT JOIN MS_PESSOA B21 ON B21.HANDLE = B19.DESTINATARIO
$whereTexto
)   
SELECT * FROM ORDENS A WHERE row_number BETWEEN $start AND $length
";

$queryOrdens = $connect->prepare($sqlOrdens);
$queryOrdens->execute();

$ordens = [];

while ($dados = $queryOrdens->fetch(PDO::FETCH_ASSOC)) {
	$dados["HANDLE"] = $dados["HANDLE"];
    $dados["STATUS"] = Sistema::getImagem($dados['RESOURCENAME'], $dados['STATUSNOME']);    
	$dados["DOCUMENTO"] = $dados["DOCUMENTO"];	
    $dados["DATAEMISSAO"] = Sistema::formataData($dados["DATAEMISSAO"]);
    $dados["PRAZOENTREGA"] = Sistema::formataData($dados["PRAZOENTREGA"]);
    $dados["PREVISAOENTREGA"] = Sistema::formataData($dados["PREVISAOENTREGA"]);
    $dados["ENTREGUEEM"] = Sistema::formataDataHora($dados["ENTREGUEEM"]);    
    $dados["PESO"] = Sistema::formataValor($dados["PESO"]);
    $dados["PESOCUBADO"] = Sistema::formataValor($dados["PESOCUBADO"]);
    $dados["PESOLOTACAO"] = Sistema::formataValor($dados["PESOLOTACAO"]);
    $dados["VOLUME"] = Sistema::formataValor($dados["VOLUME"]);
    $dados["VALORBRUTO"] = Sistema::formataValor($dados["VALORBRUTO"]);
    $dados["QUANTIDADE"] = Sistema::formataValor($dados["QUANTIDADE"]);
	$dados["VALORMERCADORIA"] = Sistema::formataValor($dados["VALORMERCADORIA"]);	

    $ordens[] = $dados;
}

$sqlOrdensFiltro = "SELECT COUNT(A.HANDLE) FILTRADO
FROM OP_AGRUPAMENTO A  
LEFT JOIN GD_DOCUMENTO B3 ON B3.HANDLE = A.DOCUMENTO
LEFT JOIN GD_DOCUMENTOTRANSPORTE B1 ON B1.HANDLE = B3.DOCUMENTOTRANSPORTE
LEFT JOIN GD_STATUSDOCUMENTOTRANSPORTE B2 ON B1.STATUS = B2.HANDLE 
AND ((NOT EXISTS (SELECT HANDLE 
			FROM MS_OPERACAOPAPELUSUARIO 
			WHERE OPERACAO = B3.OPERACAO)
 OR EXISTS (SELECT HANDLE 
			FROM MS_OPERACAOPAPELUSUARIO 
             
			WHERE OPERACAO = B3.OPERACAO 
			AND PAPEL IN (SELECT PAPEL 
				FROM MS_USUARIOPAPEL 
                                                              
				WHERE USUARIO = $usuario))))  
AND ((B3.EHRH <> 'S') OR (EXISTS (SELECT Z0.HANDLE                                             
			FROM MS_USUARIOPAPEL Z0                                            
			INNER JOIN MS_PAPEL Z1 ON Z1.HANDLE = Z0.PAPEL                                            
			WHERE Z0.USUARIO = $usuario                                              
			AND Z1.EHVISUALIZARRECURSOSHUMANOS <> 'S'))) 
LEFT JOIN TR_TIPODOCUMENTO B4 ON B3.TIPODOCUMENTOFISCAL = B4.HANDLE 
LEFT JOIN MS_FILIAL B5 ON B3.FILIAL = B5.HANDLE 
LEFT JOIN MS_FILIAL B6 ON B1.FILIALTRANSPORTE = B6.HANDLE 
LEFT JOIN MS_PESSOA B7 ON A.TRANSPORTADOR = B7.HANDLE 
LEFT JOIN MS_MUNICIPIO B8 ON B1.MUNICIPIOORIGEM = B8.HANDLE 
LEFT JOIN MS_ESTADO B9 ON B8.ESTADO = B9.HANDLE 
LEFT JOIN MS_MUNICIPIO B10 ON B1.MUNICIPIODESTINO = B10.HANDLE 
LEFT JOIN MS_ESTADO B11 ON B10.ESTADO = B11.HANDLE 
LEFT JOIN MS_PESSOA B12 ON B1.REMETENTE = B12.HANDLE 
LEFT JOIN MS_PESSOA B13 ON B1.DESTINATARIO = B13.HANDLE 
LEFT JOIN MS_PESSOA B14 ON B3.PESSOA = B14.HANDLE 
LEFT JOIN MT_NATUREZAMERCADORIA B15 ON B1.NATUREZAMERCADORIA = B15.HANDLE
$whereTexto";


$queryOrdensFiltro = $connect->prepare($sqlOrdensFiltro);
$queryOrdensFiltro->execute();

$filtro = $queryOrdensFiltro->fetch(PDO::FETCH_ASSOC);

$sqlOrdensTotal = "SELECT COUNT(A.HANDLE) TOTAL
FROM OP_AGRUPAMENTO A  
LEFT JOIN GD_DOCUMENTO B3 ON B3.HANDLE = A.DOCUMENTO
LEFT JOIN GD_DOCUMENTOTRANSPORTE B1 ON B1.HANDLE = B3.DOCUMENTOTRANSPORTE
LEFT JOIN GD_STATUSDOCUMENTOTRANSPORTE B2 ON B1.STATUS = B2.HANDLE 
AND ((NOT EXISTS (SELECT HANDLE 
			FROM MS_OPERACAOPAPELUSUARIO 
			WHERE OPERACAO = B3.OPERACAO)
 OR EXISTS (SELECT HANDLE 
			FROM MS_OPERACAOPAPELUSUARIO 
             
			WHERE OPERACAO = B3.OPERACAO 
			AND PAPEL IN (SELECT PAPEL 
				FROM MS_USUARIOPAPEL 
                                                              
				WHERE USUARIO = $usuario))))  
AND ((B3.EHRH <> 'S') OR (EXISTS (SELECT Z0.HANDLE                                             
			FROM MS_USUARIOPAPEL Z0                                            
			INNER JOIN MS_PAPEL Z1 ON Z1.HANDLE = Z0.PAPEL                                            
			WHERE Z0.USUARIO = $usuario                                              
			AND Z1.EHVISUALIZARRECURSOSHUMANOS <> 'S'))) 
LEFT JOIN TR_TIPODOCUMENTO B4 ON B3.TIPODOCUMENTOFISCAL = B4.HANDLE 
LEFT JOIN MS_FILIAL B5 ON B3.FILIAL = B5.HANDLE 
LEFT JOIN MS_FILIAL B6 ON B1.FILIALTRANSPORTE = B6.HANDLE 
LEFT JOIN MS_PESSOA B7 ON A.TRANSPORTADOR = B7.HANDLE 
LEFT JOIN MS_MUNICIPIO B8 ON B1.MUNICIPIOORIGEM = B8.HANDLE 
LEFT JOIN MS_ESTADO B9 ON B8.ESTADO = B9.HANDLE 
LEFT JOIN MS_MUNICIPIO B10 ON B1.MUNICIPIODESTINO = B10.HANDLE 
LEFT JOIN MS_ESTADO B11 ON B10.ESTADO = B11.HANDLE 
LEFT JOIN MS_PESSOA B12 ON B1.REMETENTE = B12.HANDLE 
LEFT JOIN MS_PESSOA B13 ON B1.DESTINATARIO = B13.HANDLE 
LEFT JOIN MS_PESSOA B14 ON B3.PESSOA = B14.HANDLE 
LEFT JOIN MT_NATUREZAMERCADORIA B15 ON B1.NATUREZAMERCADORIA = B15.HANDLE
$whereTexto";


$queryOrdensTotal = $connect->prepare($sqlOrdensTotal);
$queryOrdensTotal->execute();

$total = $queryOrdensTotal->fetch(PDO::FETCH_ASSOC);

echo json_encode([
    "draw" => $_GET['draw'],
    "recordsTotal" => $total["TOTAL"],
    "recordsFiltered" => $filtro["FILTRADO"],
    "data" => $ordens
]);