<?php
	include_once('../tecnologia/Sistema.php');

	$connect = Sistema::getConexao();
	
	$rastreamento = Sistema::getPost('rastreamento');
	    
	$dados = " SELECT A.HANDLE, 
			   A.STATUS, 
			   A.NUMERO, 
			   C.NOME FILIAL, 
			   A.DATA, 
			   A.RASTREAMENTO, 
			   A.VALORMERCADORIA, 
			   D.APELIDO REMETENTE, 
			   E.APELIDO DESTINATARIO, 
			   I.NOME MUNICIPIOCOLETA, 
			   K.SIGLA ESTADOCOLETA, 
			   J.NOME MUNICIPIOENTREGA, 
			   L.SIGLA ESTADOENTREGA,
			   N.NOME TIPO,
			   A.QUANTIDADE,
			   A.VOLUME,
			   A.PESO,
			   A.DATACOLETA,
			   A.DATAENTREGAATE,
			   A.DATAENTREGA,
			   O.NOME BAIRROCOLETA,
			   P.NOME BAIRROENTREGA,
			   G.LOGRADOURO RUACOLETA,
			   H.LOGRADOURO RUAENTREGA,
			   G.NUMERO NUMEROCOLETA,
			   H.NUMERO NUMEROENTREGA,
			   Q.CEP CEPCOLETA,
			   R.CEP CEPENTREGA,
			   S.NOME PAISCOLETA,
			   T.NOME PAISENTREGA,
			   U.DOCUMENTO,
			   X.NOME RAZAOSOCIALEMPRESA,
			   X.CNPJCPF CNPJCPFEMPRESA,
			   A.RASTREAMENTO
			FROM RA_PEDIDO A (NOLOCK)
			LEFT JOIN RA_STATUSPEDIDO B ON A.STATUS = B.HANDLE 
			LEFT JOIN MS_FILIAL C ON A.FILIAL = C.HANDLE
			LEFT JOIN MS_PESSOA D ON A.REMETENTE = D.HANDLE 
			LEFT JOIN MS_PESSOA E ON A.DESTINATARIO = E.HANDLE 
			LEFT JOIN MS_USUARIO F ON A.LOGUSUARIOCADASTRO = F.HANDLE
			LEFT JOIN MS_PESSOAENDERECO G ON A.ENDERECOLOCALCOLETA = G.HANDLE
			LEFT JOIN MS_PESSOAENDERECO H ON A.ENDERECOLOCALENTREGA = H.HANDLE
			LEFT JOIN MS_MUNICIPIO I ON G.MUNICIPIO = I.HANDLE
			LEFT JOIN MS_MUNICIPIO J ON H.MUNICIPIO = J.HANDLE
			LEFT JOIN MS_ESTADO K ON G.ESTADO = K.HANDLE
			LEFT JOIN MS_ESTADO L ON H.ESTADO = L.HANDLE
			LEFT JOIN RA_STATUSPEDIDO M ON A.STATUS = M.HANDLE
			LEFT JOIN RA_TIPOPEDIDO N ON A.TIPO = N.HANDLE
			LEFT JOIN MS_BAIRRO O ON G.BAIRRO = O.HANDLE
			LEFT JOIN MS_BAIRRO P ON H.BAIRRO = P.HANDLE
			LEFT JOIN MS_CEP Q ON G.CEP = Q.HANDLE
			LEFT JOIN MS_CEP R ON H.CEP = R.HANDLE
			LEFT JOIN MS_PAIS S ON Q.PAIS = S.HANDLE
			LEFT JOIN MS_PAIS T ON R.PAIS = T.HANDLE
			LEFT JOIN RA_PEDIDODOCUMENTO U ON A.HANDLE = U.PEDIDO
			LEFT JOIN MS_EMPRESA V ON A.EMPRESA = V.HANDLE
			LEFT JOIN MS_PESSOA X ON V.PESSOA = X.HANDLE
			WHERE A.RASTREAMENTO = '".$rastreamento."' 
			";
							   
	$dados = $connect->prepare($dados);
	
	$dados->execute();
	
	$dadosRetorno = array();

    $result = $dados->fetch(PDO::FETCH_ASSOC);
	
    echo json_encode($result);	
	
?>